name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '16.x'
      env:
        PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'
    - name: Install dependencies
      run: yarn
    - name: Build extension for Chromium
      run: yarn build
    - name: Run Playwright tests for Chromium
      uses: mujo-code/puppeteer-headful@v2
      env:
        CI: 'true'
      with:
        args: yarn playwright test --project=chromium
