env:
    DIRECTORY: distribution

name: Release
on:
    workflow_dispatch: null
jobs:
    Version:
        outputs:
            created: ${{ steps.daily-version.outputs.created }}
            version: ${{ steps.daily-version.outputs.version }}
            upload_url: ${{ steps.latest_release_info.outputs.upload_url }}
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: fregante/daily-version-action@v1
              name: Create tag if necessary
              id: daily-version
            - uses: fregante/release-with-changelog@v3
              if: steps.daily-version.outputs.created
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
            - name: Sleep for 10 seconds
              uses: whatnick/wait-action@master
              with:
                time: '10s'
            - name: Get release
              if: steps.daily-version.outputs.created
              id: latest_release_info
              uses: jossef/action-latest-release-info@v1.1.0
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    Build:
        needs: Version
        if: github.event_name == 'workflow_dispatch' || needs.Version.outputs.created
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - name: install
            run: yarn install
          - name: build
            run: yarn build
          - name: Update extension meta
            run: >-
                npx dot-json@1 $DIRECTORY/manifest.json version ${{
                needs.Version.outputs.version }}
          - name: package
            run: npx web-ext build
          - name: upload artifact
            uses: actions/upload-release-asset@v1
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            with:
              upload_url: ${{ needs.Version.outputs.upload_url }}
              asset_path: ./web-ext-artifacts/lindylearn_annotations-${{ needs.Version.outputs.version }}.zip
              asset_name: lindylearn_annotations-${{ needs.Version.outputs.version }}.zip
              asset_content_type: application/zip
    # Submit:
    #     needs: Version
    #     if: github.event_name == 'workflow_dispatch' || needs.Version.outputs.created
    #     strategy:
    #         fail-fast: false
    #         matrix:
    #             command:
    #                 - firefox
    #                 - chrome
    #     runs-on: ubuntu-latest
    #     steps:
    #         - uses: actions/checkout@v2
    #         - name: install
    #           run: yarn install
    #         - name: build
    #           run: yarn build
    #         - name: Update extension meta
    #           run: >-
    #               npx dot-json@1 $DIRECTORY/manifest.json version ${{
    #               needs.Version.outputs.version }}
    #         - name: Submit
    #           run: |
    #               case ${{ matrix.command }} in
    #                 firefox)
    #                   cd $DIRECTORY && npx web-ext-submit@6
    #                   ;;
    #                 chrome)
    #                   cd $DIRECTORY && npx chrome-webstore-upload-cli@1 upload --auto-publish
    #                   ;;
    #               esac
    #           env:
    #               EXTENSION_ID: ${{ secrets.EXTENSION_ID }}
    #               CLIENT_ID: ${{ secrets.CLIENT_ID }}
    #               CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
    #               REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
    #               WEB_EXT_API_KEY: ${{ secrets.WEB_EXT_API_KEY }}
    #               WEB_EXT_API_SECRET: ${{ secrets.WEB_EXT_API_SECRET }}
